/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebookIdRouteImport } from './routes/notebook.$id'

const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIdRoute = NotebookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotebookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notebook': typeof NotebookRouteWithChildren
  '/notebook/$id': typeof NotebookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notebook': typeof NotebookRouteWithChildren
  '/notebook/$id': typeof NotebookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notebook': typeof NotebookRouteWithChildren
  '/notebook/$id': typeof NotebookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notebook' | '/notebook/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notebook' | '/notebook/$id'
  id: '__root__' | '/' | '/notebook' | '/notebook/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotebookRoute: typeof NotebookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$id': {
      id: '/notebook/$id'
      path: '/$id'
      fullPath: '/notebook/$id'
      preLoaderRoute: typeof NotebookIdRouteImport
      parentRoute: typeof NotebookRoute
    }
  }
}

interface NotebookRouteChildren {
  NotebookIdRoute: typeof NotebookIdRoute
}

const NotebookRouteChildren: NotebookRouteChildren = {
  NotebookIdRoute: NotebookIdRoute,
}

const NotebookRouteWithChildren = NotebookRoute._addFileChildren(
  NotebookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotebookRoute: NotebookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
