export const LANGUAGES = [
    { name: "English", code: "en" },
    { name: "Spanish", code: "es" },
    { name: "French", code: "fr" },
    { name: "German", code: "de" },
    { name: "Chinese (Simplified)", code: "zh-CN" },
    { name: "Chinese (Traditional)", code: "zh-TW" },
    { name: "Japanese", code: "ja" },
    { name: "Korean", code: "ko" },
    { name: "Portuguese", code: "pt" },
    { name: "Russian", code: "ru" },
    { name: "Italian", code: "it" },
    { name: "Dutch", code: "nl" },
    { name: "Arabic", code: "ar" },
    { name: "Hindi", code: "hi" },
    { name: "Turkish", code: "tr" },
    { name: "Polish", code: "pl" },
    { name: "Vietnamese", code: "vi" },
    { name: "Thai", code: "th" },
    { name: "Indonesian", code: "id" },
    { name: "Malay", code: "ms" },
    { name: "Swedish", code: "sv" },
    { name: "Danish", code: "da" },
    { name: "Norwegian", code: "no" },
    { name: "Finnish", code: "fi" },
    { name: "Greek", code: "el" },
    { name: "Hebrew", code: "he" },
    { name: "Czech", code: "cs" },
    { name: "Romanian", code: "ro" },
    { name: "Hungarian", code: "hu" },
    { name: "Ukrainian", code: "uk" },
] as const;

export type LanguageCode = typeof LANGUAGES[number]["code"];
